### ISSUE TITLE
Line #170 is writing frowny faces

### ISSUE THREAD

**Issue by creativereason** [jakezatecky/d3-funnel#11]
Happened for me in both min and regular js version. In `d3-funnel.js` it's on line #170. 

		console.log(":(");

**Comment by creativereason** [comment]
Note, thanks by the way for this awesome javascript, I just remember console.log messages causing errors on some version of IE.

**Comment by jakezatecky** [comment]
Yeah, I noticed that a while back. It was fixed in 343be91120392b7ff5200ef9c744cfdfb7b61e39, but I  neglected to produce the distribution files.

I tagged a 0.6.6 release and updated the NPM package (I screwed up the 0.6.5 release).
