### ISSUE TITLE
FunnelGraph call fail

### ISSUE THREAD

**Issue by maristhek** [jakezatecky/d3-funnel#121]
funnel-graph.js:147 Uncaught TypeError: Invalid attempt to spread non-iterable instance
    at _nonIterableSpread (funnel-graph.js:147)
    at _toConsumableArray (funnel-graph.js:145)
    at FunnelGraph.createPercentages (funnel-graph.js:452)
    at new FunnelGraph (funnel-graph.js:171)
    at NewFunnel:59

 What does this mean.  Running sample code as described in README.md on .NET Core MVC 

@page
@{
}
<head>
    <link rel="stylesheet" type="text/css" href="~/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/css/theme.css">
</head>
     <script src="~/js/funnel-graph.js"></script>

<script>
    var graph=new FunnelGraph({
        container: '.funnel',
        gradientDirection: 'horizontal',
        data: [12000,5700,360],
        displayPercent: true,
        direction: 'horizontal'
    });

    graph.draw();
</script>

**Comment by jakezatecky** [comment]
Hello, this library's object `D3Funnel`, not `FunnelGraph`, which leads me to believe you are using a different library, or at least a library that has abstracted this component.

**Comment by maristhek** [comment]
The code was cloned in a repo that looked almost the same as yours.  Could have been from npmjs.
The clone fro github works as expected.
