### ISSUE TITLE
Tooltip position incorrect in latest versions of Chrome

### ISSUE THREAD

**Issue by yeagernation** [jakezatecky/d3-funnel#138]
In Chrome, something appears to have changed with the tooltips. They are now off to the upper left hand side of the screen. Appears to still work in other broswers and just noticed on Chrome when it was brought to my attention. Happening on Mac and Windows versions. Verified on Mac 87.0.4280.88

[Screenshot on d3-funnel example page](https://www.dropbox.com/s/zp9m8m7p8n0k13b/screen%20shot%202021-01-12%20at%2011.52.47%20am.png?dl=0)

**Comment by iamkryptonite** [comment]
Same issue. Have you resolved it?

**Comment by yeagernation** [comment]
> Same issue. Have you resolved it?

No,  I didn't have any luck. Would love to find a fix.

**Comment by jakezatecky** [comment]
Verified.
