### ISSUE TITLE
Opacity in fill of d3-funnel

### ISSUE THREAD

**Issue by priyanshi0799** [jakezatecky/d3-funnel#140]
I am trying to add rgba value to the data but in the background, it is getting converted to hex code, leaving the opacity.
How can I fix it?
![image](https://user-images.githubusercontent.com/48996188/104710568-3dbc2600-5746-11eb-9b11-7d4558c5cd15.png)
 
This is my data array value.

**Comment by jakezatecky** [comment]
Hey there. This library does not support `rgba` values as of this moment. Much of the color-related calculations assume a hex format. Although it is reasonable to consider adding support for `rgb`/`rgba` values in the future, it is easier for now to just add proper support for `opacity`. I will add this as a future enhancement.

Side note: the format you are using for data conforms to the deprecated array-style.

**Comment by priyanshi0799** [comment]
@jakezatecky thanks.
