### ISSUE TITLE
Add support for formatted labels

### ISSUE THREAD

**Issue by stefanwalther** [jakezatecky/d3-funnel#16]
I am thinking of adding a pull-request to allow formatted values to be displayed. So in my solution you can do either

```javascript
var data = [
    ["Teal",      12000, "#008080"],
    ["Byzantium", 4000,  "#702963"],
    ["Persimmon", 2500,  "#ff634d"],
    ["Azure",     1500,  "#007fff"]
];
```

or

```javascript
var data = [
    ["Teal",      [12000, 'EUR 12,000'], "#008080"],
    ["Byzantium", [4000, 'EUR 4,000'],  "#702963"],
    ["Persimmon", [2500, 'EUR 2,500'],  "#ff634d"],
    ["Azure",     [1500, 'EUR 1,500'],  "#007fff"]
];
```

Does this sound good for you?

Regards
Stefan

**Comment by jakezatecky** [comment]
I agree that adding support for custom labels is desirable. Observing some other libraries, I think it might be advantageous to allow for a label formatter and a simple text template. E.g, I was thinking.:

``` javascript
{
    // %l label
    // %v raw value
    // %f formatted value (value.toLocaleString())
    label: {
        // Teal - USD 12000
        format: '%l - USD %v',
        // Teal: USD 12,000
        format: '%l: USD %f',
        // Teal: $12,000
        format: function(label, value) {
            return label+ ": $" + value.toLocaleString();
        }
    }
}
```

Of course, this would not allow for the fine row-level granularity that your solution offers, but it would offer more flexibility in how the label is positioned. In the worst case, the user could call a method of some prototyped object whose member variable would have these row-level labels.

I'm hesitant to add even more to the data definition, but this could be considered a viable solution "for now" as well as an optional way to specify custom labels when a more powerful implementation is available.

**Comment by stefanwalther** [comment]
Hi,

while I understand your standpoint my background to develop this was a bit different. I was using your solution for a visualization extension in Qlik Sense (https://github.com/stefanwalther/qsFunnel/) and in this case our engine is able to deliver a so called "dual value", containing both, a numeric value and a formatted value.
Therefore the formatted labels wouldn't help ... maybe you can think of supporting both approaches?

Regards
Stefan
