### ISSUE TITLE
How to destroy chart?

### ISSUE THREAD

**Issue by thelinuxlich** [jakezatecky/d3-funnel#21]

**Comment by jakezatecky** [comment]
Good question. I went ahead and added a method to destroy the funnel. In case you do not have access to the D3Funnel instance, you can also do the following:

``` javascript
d3.select('#chart').selectAll('svg').remove();
```

**Comment by jimmydave03** [comment]
Thanks  @jakezatecky I was able to remove my d3 chart with this.
