### ISSUE TITLE
Error on implementation

### ISSUE THREAD

**Issue by wouteronline55** [jakezatecky/d3-funnel#22]
Hi,

I'm trying to implement your d3-funnel library, but I'm getting "Unexpected token =>" message from the browser for line 1 of the d3-funnel.js file. 

I've tried several things already:
- Changing order or loading
- Changing Jquery version
- Removing all other JS from the page

Any ideas what I'm doing wrong?

Wouter

**Comment by jakezatecky** [comment]
Are you using the `/src/d3-funnel.js` file? This will not work in most browsers, as it contains ES6 JavaScript. The compiled version to use is `/dist/d3-funnel.js`.

**Comment by wouteronline55** [comment]
Yeah, you're right! Thanks!
