### ISSUE TITLE
Trouble with Alert boxes

### ISSUE THREAD

**Issue by bigboy6** [jakezatecky/d3-funnel#24]
How do I implement the alerts boxes like you have on the example site.
http://jakezatecky.github.io/d3-funnel/

The drop down is fine but I am looking to utilize the alert boxes to provide the users with additional information per funnel segment..

This is what I posted on Stackoverflow
http://stackoverflow.com/questions/32010822/javascript-alert-box-using-d3-charting/

Thanks..

**Comment by jakezatecky** [comment]
I am not quite sure what you are trying to accomplish.

The alerts that occur in the example utilize the `onItemClick` event:

``` javascript
var data = [
	['Applicants',   12000],
	['Pre-screened', 4000],
	['Interviewed',  2500],
	['Hired',        1500]
];
var options = {
	onItemClick: function(d, i) {
		alert('<' + d.label + '> selected.');
	}
};

var funnel = new D3Funnel('#funnel');
funnel.draw(data, options);
```

**Comment by bigboy6** [comment]
When downloading the example file it seems that the selection for the OnClickEvent was removed and I am trying to understand how to implement. 
Also for what you provided above: ```Var data``` and ```Var options``` ~ these both go in the ```index.html```, correct?
As for ```var funnel``` ~ where does this function get placed?

Thanks

**Comment by bigboy6** [comment]
This is what I have for HTML (from your site) so where does the onItemClick event get placed?
~Thanks

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>D3 Funnel</title>
		<link rel="stylesheet" href="httpmaxcdn.bootstrapcdn.combootstrap3.3.4cssbootstrap.css">
		<link rel="stylesheet" href="style.css">
	</head>
	<body>
		<div class="container">
			<h1>D3 Funnel</h1>
			<div class="example">
				<form class="form-inline">
					<select class="form-control" id="picker">
						<option value="basic">No options</option>
						<option value="formatted">Formatted values</option>
						<option value="curved">Curved</option>
						<option value="pinch">Pinched</option>
						<option value="gradient">Gradient</option>
						<option value="inverted">Inverted</option>
						<option value="hover">Hover effects</option>
						<option value="dynamic">Dynamic area</option>
						<option value="minHeight">Minimum height</option>
						<option value="animation">Animation</option>
						<option value="label">Styling labels</option>
						<option value="color">Custom colors</option>
						<option value="labelsColor">Custom label colors</option>
						<option value="works">The Works</option>
					</select>
				</form>
				
				<div id="funnel"></div>
			</div>
		</div>

		
		<script src="httpcdnjs.cloudflare.comajaxlibsd33.5.5d3.js"></script>
		
		<script src="d3-funnel.js"></script>

		
		<script src="httpcode.jquery.comjquery-2.1.4.js"></script>

		<script>
			$(function() {
				$('#picker').change(function() {
					var index = $(this).val();

					var data = {
						normal: [
							['Applicants',   12000],
							['Pre-screened', 4000],
							['Interviewed',  25000],
							['Hired',        1500]
						],
						formattedValues: [
							['Applicants',   [12000, '$12,000']],
							['Pre-screened', [4000,  '$4,000']],
							['Interviewed',  [2500,  '$2,500']],
							['Hired',        [1500,  '$1,500']]
						],
						minHeight: [
							['Applicants',   12000],
							['Pre-screened', 4000],
							['Interviewed',  2500],
							['Hired',        100]
						],
						color:  [
							['Teal',      12000, '#008080'],
							['Byzantium', 4000,  '#702963'],
							['Persimmon', 2500,  '#ff634d'],
							['Azure',     1500,  '#007fff']
						],
						labelsColor: [
							['Teal',      12000, '#008080', '#080800'],
							['Byzantium', 4000,  '#702963'],
							['Persimmon', 2500,  '#ff634d', '#6f34fd'],
							['Azure',     1500,  '#007fff', '#07fff0']
						]
					};

					var options = {
						basic: [data.normal, {}],
						formatted: [
							data.formattedValues,
							{}
						],
						curved: [
							data.normal, {
								isCurved: true
							}
						],
						pinch: [
							data.normal, {
								bottomPinch: 1
							}
						],
						gradient: [
							data.normal, {
								fillType: 'gradient'
							}
						],
						inverted: [
							data.normal, {
								isInverted: true
							}
						],
						hover: [
							data.normal, {
								hoverEffects: true
							}
						],
						dynamic: [
							data.normal, {
								dynamicArea: true
							}
						],
						minHeight: [
							data.minHeight, {
								dynamicArea: true,
								minHeight: 10
							}
						],
						animation: [
							data.normal, {
								animation: 200
							}
						],
						label: [
							data.normal, {
								label: {
									fontSize: '16px',
									fill: '#000'
								}
							}
						],
						color: [data.color, {}],
						labelsColor: [data.labelsColor, {}],
						works: [
							data.normal, {
								isCurved: true,
								bottomPinch: 2,
								fillType: 'gradient',
								hoverEffects: true,
								dynamicArea: true,
								animation: 200
							}
						]
					};

					var chart = new D3Funnel('#funnel');

					// Reverse the dataset if the isInverted option is present
					// Keep in mind that because the larger component has shorter
					// width, it must compensate with a much larger height!
					if (options[index].hasOwnProperty('isInverted')) {
						chart.draw(data.reverse(options[index][0]), options[index][1]);
					// Otherwise, just use the regular data
					} else {
						chart.draw(options[index][0], options[index][1]);
					}
				}).trigger('change');
			});
		</script>
	</body>
</html>

**Comment by jakezatecky** [comment]
As I said above, you can add the `onItemClick` option. For example, you can modify `works` to the following:

``` javascript
works: [
    data.normal, {
        isCurved: true,
        bottomPinch: 2,
        fillType: 'gradient',
        hoverEffects: true,
        dynamicArea: true,
        animation: 200,
        onItemClick: function(d, i) {
            alert('<' + d.label + '> selected.');
        }
    }
]
```

I did not add it to the examples in the `master` branch out of pure laziness and the fact that the github.io example shows it anyway. I just added it to the examples in 8e4babf48f62dfb72396abe6c315d4d58f3385e5.
