### ISSUE TITLE
Container content not removed

### ISSUE THREAD

**Issue by jonathanmv** [jakezatecky/d3-funnel#36]
Hi,

If you have any content in the funnel container it will remain after the funnel has been added. For example:

````
  <div id="funnel">Loading ...</div>
````

You can see this in the image below.

![image](https://cloud.githubusercontent.com/assets/86024/10516566/9e5e89ec-7337-11e5-8ecf-865f4e53a5ed.png)

**Comment by dossdboss** [comment]
What effort it would take to convert your funnel into something like Fusion  funnel chart.  http://www.fusioncharts.com/charts/fusionwidgets/

**Comment by jonathanmv** [comment]
Sorry, i don't get the question. Could you explain a little bit further @dossdboss please?
