### ISSUE TITLE
No 'click' events will make a console error when click

### ISSUE THREAD

**Issue by natee** [jakezatecky/d3-funnel#41]
'block' set 'null' will make an error when click.
```
events:{
    click:{
        block: null
    }
}
```
After Utils.extend(settings) , click.block will be an empty object.

**Comment by jakezatecky** [comment]
Thanks.

**Comment by mirajhad** [comment]
how to add function when a click event occurs?

**Comment by jakezatecky** [comment]
Set `events.click.block` to a function:

``` js
{
  events: {
    click: {
      block: (e) => {
        console.log(e);
      }
    }
  }
}
```

**Comment by mirajhad** [comment]
on this function 

> Set `events.click.block` to a function:
> 
> ```js
> {
>   events: {
>     click: {
>       block: (e) => {
>         console.log(e);
>       }
>     }
>   }
> }
> ```

on this function can we add zoom at each level  when we click on level.
