### ISSUE TITLE
Funnel Width Function of Value

### ISSUE THREAD

**Issue by curtw** [jakezatecky/d3-funnel#47]
Is it possible to configure the chart such that the width of a block if a function of the value for that block, such that the following would give an hour glass appearance:
` var data = [
        ['Plants',     5000],
        ['Flowers',    200],
        ['Perennials', 200],
        ['Roses',      5000]
    ];
`

**Comment by jakezatecky** [comment]
Not support yet, but it's a good idea! I'll mark this for future enhancement.

**Comment by curtw** [comment]
Cool.  Thanks!
For reference, the KendoUI Funnel Chart calls this "Dynamic Slope"  http://demos.telerik.com/kendo-ui/funnel-charts/index

**Comment by jakezatecky** [comment]
Closed with #57.
