### ISSUE TITLE
Option to use d3.js from external file when using browserify

### ISSUE THREAD

**Issue by tzachyrm** [jakezatecky/d3-funnel#48]
Large dependencies like d3.js are often loaded from CDN, and shimmed using browserify-shim.

d3-funnel sets d3 as a required dependency, which forces including d3 into the bundle.

**Comment by jakezatecky** [comment]
I am not very familiar with Browserify, as I use Webpack. In Webpack, you can specify `externals`, which in allows you to use something loaded externally (such as D3 from a CDN):

``` javascript
module.exports = {
	entry: {
		app: './entry.js',
	},
	output: {
		filename: 'app.js',
	},
	externals: {
		// Do not compile d3 with the output
		d3: 'd3',
	},
};
```

With `externals` specified, D3 will NOT be outputted to `app.js`. If `externals` is not specified, then the version pulled from npm will be outputted.

Surely Browserify has a similar option?

**Comment by jakezatecky** [comment]
Closing due to lack of response. Feel free to reply if you are still having this issue,
