### ISSUE TITLE
Progress bar look for each block

### ISSUE THREAD

**Issue by jzelenkov** [jakezatecky/d3-funnel#50]
Jake, thank you for a great library. I extended it slightly to show a funnel where each block looks like a bar chart. Would you be interested in merging adding this feature to `d3-funnel`? If so, I could tidy up the source code, add a few tests and submit a pull-request.

## example

[source code](https://github.com/jevzee/d3-funnel/pull/1)

![screen shot 2016-03-07 at 5 07 04 pm 2](https://cloud.githubusercontent.com/assets/205659/13589269/6b9f00ca-e48b-11e5-8849-4163c8416f80.png)

**Comment by jakezatecky** [comment]
Sure. Just make sure that the previous tests also succeed (I see you skipped the test for gradients, probably due to the edit at [this line](https://github.com/jevzee/d3-funnel/commit/9ea9644a7d9adf763e869e1bc07902a97a0a8a3c#diff-bc9dba57c9ad95f2a56f295d12e5787cL619)).

**Comment by stefanwalther** [comment]
That really looks great, great contribution, looking forward to a PR!

**Comment by jakezatecky** [comment]
Closed with 4935052.
