### ISSUE TITLE
README example code are buggy

### ISSUE THREAD

**Issue by d4mk0** [jakezatecky/d3-funnel#6]
Hi! Today i seen next bug.

When i call **draw** function in next code:
```javascript
var data = [
    ["Plants",     5000],
    ["Flowers",    2500],
    ["Perennials", 200],
    ["Roses",      50]
];

var chart = new D3Funnel("#funnel");
chart.draw(data);
```
I have next js error:
> Uncaught TypeError: undefined is not a function d3-funnel.js?body=1:308
> D3Funnel._makePaths d3-funnel.js?body=1:308
> D3Funnel.draw d3-funnel.js?body=1:95

Error occurs in this line:
```javascript
count = this.data[i][1].replace(/\,/g, "")
```

Then i use string instead int type it works.
i.e.
```javascript
var data = [
    ["Plants",     "5000"],
    ["Flowers",    "2500"],
    ["Perennials", "200"],
    ["Roses",      "50"]
];
```

Versions:
> jquery - 1.11.1
> d3 - 3.5.2

**Comment by jakezatecky** [comment]
That's embarrassing.

I honestly don't know why I was trying to parse the counts to begin with. I made it to where numeric values are now required and that the numbers are formatted to the browser's locale when the funnel is rendered.
