### ISSUE TITLE
Why do you use jquery in examples instead of D3 itself?

### ISSUE THREAD

**Issue by yoosofan** [jakezatecky/d3-funnel#60]
This library is powered by  d3js but jquery  is used in examples while d3js can be used instead of d3js in most situations specially examples of this library. Using a lot of different libraries in projects would slow down the clients and even local servers.
Please explain why do you use jquery?

**Comment by jakezatecky** [comment]
Just out of habit. No particular reason. I suppose I should make the examples less dependent on jQuery.
