### ISSUE TITLE
Require/Define d3.js

### ISSUE THREAD

**Issue by balexbyrd** [jakezatecky/d3-funnel#65]
I'm having an issue with the require/define statement. In Qlik Sense, the funnel shows up just fine with no errors, in a mashup I'm having an issue loading d3.js from the url that is generated from the define statement.  When I comment or change the define line, it no longer works in QS (and still doesn't work in Mashup). 

Any way to just force the d3.js to load?
Any help? Thanks in advance this is fantastic

QS Works:
![image](https://cloud.githubusercontent.com/assets/4423090/17138236/4c775616-530d-11e6-9b18-16d360c56e32.png)

Error received in mashup:
![image](https://cloud.githubusercontent.com/assets/4423090/17137886/8830d5c6-530b-11e6-89c5-e148b56215c7.png)

![image](https://cloud.githubusercontent.com/assets/4423090/17138358/e518fe1a-530d-11e6-9a26-23ca6fce7fc0.png)

**Comment by balexbyrd** [comment]
I figured it out. Qlik calls define() in a mashup and the code below is required (pun intended) right before the mashup define to point to the right d3.js file. 

When define(["d3"], factory) is called it then points to the CDN below. 

`
require.config( {
	paths: {
		d3: "//cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3"
	}
});
`

**Comment by jakezatecky** [comment]
That's good. Note that I do not have that much familiarity with Qlik. Obligatory mention of the Qliksense plugin:

https://github.com/stefanwalther/sense-funnel-chart

**Comment by balexbyrd** [comment]
No worries mate, that extension you posted is using a version of your funnel from back in the day. I started with that and it required updating which leads me here. Thanks again - great work
