### ISSUE TITLE
problem with the samples

### ISSUE THREAD

**Issue by gunnarahlberg** [jakezatecky/d3-funnel#66]
Hi
The samples seems to work fine with version 0.77 of funnel and version 3 of d3
I get javascript errors when I use version 1.0 of funnel and version 4 of d3. 

Can you reproduce? I'll try to help you
//Gunnar

**Comment by jakezatecky** [comment]
I cannot reproduce any problems based on your short description. Both the examples and Github Pages are using D3 v4 and D3Funnel v1.0 without issues and all of the tests pass. You're going to have provide something more concrete.

**Comment by gunnarahlberg** [comment]
Well now the examples page certainly link to latest versions. Thank you! You can close the issue
