### ISSUE TITLE
funnel scaling with values larger than the first

### ISSUE THREAD

**Issue by acarridice** [jakezatecky/d3-funnel#68]
I'd like to use the funnel chart with data values that don't all necessarily decrease. In other words, it would be possible to see a bulge in the funnel as it goes down. 

My problem is, the funnel chart is drawn with the assumption that the first value will be the largest, and as a result, the largest values in my data exceed the canvas and are cut off on the sides.
Would it be possible to get the largest value from the data first (d3.max)? and then draw the chart with a proportional scale?

**Comment by jakezatecky** [comment]
I think at the moment too many assumption are made with scaling from largest to smallest. May re-look at this sometime in the future when the core drawing components are refactored. Unless you are willing to submit a PR with some test cases.

**Comment by TrueShutDown** [comment]
Any solutions? 
I have same problem
https://codepen.io/trueshutdown/pen/Prvqpv
