### ISSUE TITLE
Add ability to hide some labels while showing others

### ISSUE THREAD

**Issue by tmthyjames** [jakezatecky/d3-funnel#71]
Great library. 

I want to be able to hide some labels and show others because if a certain value is dwarfed by other values to the point where their section of the funnel is only a few pixels in height, then their labels don't adjust and it looks cluttered.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/8451865/22432290/0e8136cc-e6da-11e6-8be7-5e5ae107f559.png)

Notice the categories in the middle. 

If this is already possible, I will be happy to close this ticket. If not, I'd be happy to give it a go.

**Comment by jakezatecky** [comment]
I have been considering adding an option to hide labels globally, specifically in consideration of #10 and #45, but did not plan for anything on a block-level.

I suppose this could be added, but I hesitant to add yet another index to the existing data structure array. I think it might be appropriate to allow for an object to be used in place of an array; that would make it cleaner to allow block-level customizations like hiding labels. I'll consider making that a feature that has backwards compatibility with the existing data structure.

In the interim, you might consider setting a minimum height, such that each block is guaranteed to have a height large enough to support the text:

``` javascript
const options = {
    block: {
        dynamicHeight: true,
        minHeight: 25,
    },
};
```
