### ISSUE TITLE
D3Funnel is not defined

### ISSUE THREAD

**Issue by bgauthier** [jakezatecky/d3-funnel#72]
Hello,

Trying out the library, if I include the js script dist/d3-funnel.min.js, the js file loads in the browser I can see it in Chrome debugger but the DBFunnel object doesn't seem to exist. What am i missing?

Thank you very much.

**Comment by jakezatecky** [comment]
Hey there. Are you sure that you have the D3 library also loaded in your browser? You can look at the example I just created below, showing d3 and d3-funnel loaded in the browser and the library working as expected:

https://jsfiddle.net/qk4agc65/1/
