### ISSUE TITLE
Plugin installation was unsuccessful due to error "Optimizations failure.

### ISSUE THREAD

**Issue by Jal619** [jakezatecky/d3-funnel#76]
Hi,
We tried to install d3-Funnel visualization in Kibana 5.4.0.
We got below error during installation.

D:\xxx\xxx\Elastic_Search\kibana-5.4.0-windows-x86\kibana-5.4.0-windows-x86\b
in>kibana-plugin install file:///D:/xxx/xxx/Elastic_Search/Kibana.zip
Found previous install attempt. Deleting...
Attempting to transfer from file:///D:/xxx/xxxx/Elastic_Search/Kibana.zip
Transferring 5829992 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ../plugins/ob-kb-funnel/public/funnelController.js
    Module not found: Error: Cannot resolve module 'd3-funnel' in D:\xxx\xxx\Elastic_Search\kibana-5.4.0-windows-x86\kibana-5.4.0-windows-x86\plugins\ob-kb-funnel\public     @ ../plugins/ob-kb-funnel/public/funnelController.js 6:15-35
"

Please help.

Thanks & Regards,
Jalpesh

**Comment by jakezatecky** [comment]
I have never used Kibana before, so I am quite unaware of how their ecosystem works. If you attached the `funnelController.js` that is being referenced, I could possibly take a quick look, but it seems as through the error being reported is likely correct: it cannot resolve the module. Possibly d3-funnel is not located where it is expected. If it uses npm, it may not have been downloaded. It's too difficult to tell.

**Comment by jakezatecky** [comment]
Please contact the author of that plugin.

https://github.com/outbrain/ob-kb-funnel
