### ISSUE TITLE
Chart doesn't display

### ISSUE THREAD

**Issue by PankajB1997** [jakezatecky/d3-funnel#77]
Used the exact same example as given in the doc. Also tried the index.html file in examples/dist directory. Both the pages will load all the other elements, but the chart itself is not displayed at all.

**Comment by sidzan** [comment]
i am also facing the same issue, i am using react. The chart seems to be rendered but the svg contents is loaded with 0 height (no css) . I think this is causing some issue .

**Comment by jakezatecky** [comment]
Can you link to a live example of this issue? If a height of zero is being experienced, you may have to set a `width` and `height` on the container div. The library tries to utilize any existing height/width specifications on this container div.

Nevertheless, it *should* be setting a default width and height if it cannot determine one. I might have to look as to why that is not getting set.

**Comment by jakezatecky** [comment]
Confirmed that neglecting to have any width or height added to the container did not trigger the library defaults.

**Comment by PankajB1997** [comment]
Thanks! It's up now. Keep up the great work!
