### ISSUE TITLE
Query: Can this be used with ReactJS?

### ISSUE THREAD

**Issue by sidzan** [jakezatecky/d3-funnel#78]
I tried to use the import , which seems to work but i am having difficulty displaying the data 

I tried to use the following in componentDidMount()

  ```
  const data = [
        ['Inquiries', 5000],
        ['Applicants', 2500],
        ['Admits', 500],
        ['Deposits', 200],
    ];
    const options = {
        block: {
            dynamicHeight: true,
            minHeight: 15,
        },
    };

    const chart = new D3Funnel('#funnel');
    chart.draw(data, options);
```

But no luck, is not working. Is this have to be defined solely inside <scripts> tag?

**Comment by jakezatecky** [comment]
This should be usable within React. As your other comment noted in #77, this might be related to a different issue. I suspect it is related to no height. You might try adding `chart.height` to your options:

``` js
const options = {
    chart: {
        height: 400,
    },
    block: {
        dynamicHeight: true,
        minHeight: 15,
    },
};
```

If that does not work, you can do the following:

``` jsx
<div id="funnel" style={{ height: 400 }} />
```

I'll look into why a default height might not be triggering in issue #77 in the meantime.

---

Nevertheless, your query reminded me that I do not like that the D3Funnel library is requiring a query selector to draw a chart. I think I'll make a small change to be able to accept a DOM node, as that is a bit more of a React way handling nodes.

**Comment by jakezatecky** [comment]
An update to #77 was pushed. Please confirm whether you experience this issue anymore.

**Comment by jakezatecky** [comment]
Closing due to lack of response.

**Comment by sidzan** [comment]
Thanks A lot ! Worked for me after update  !

**Comment by wulucxy** [comment]
@sidzan I still have this problem, [link](https://github.com/jakezatecky/d3-funnel/issues/70) this is what i encounter, so how do you solve this?

**Comment by lucaskeller** [comment]
I used refs:

```
  constructor(props) {
    super(props)
    this.funnelRef = React.createRef()
  }

```

```
<div ref={this.funnelRef} id="funnel" style={{ height: 400 }} />
```

```
const chart = new D3Funnel(this.funnelRef.current)
chart.draw(data, options)
```

**Comment by 15520528** [comment]
> I used refs:
> 
> ```
>   constructor(props) {
>     super(props)
>     this.funnelRef = React.createRef()
>   }
> ```
> 
> ```
> <div ref={this.funnelRef} id="funnel" style={{ height: 400 }} />
> ```
> 
> ```
> const chart = new D3Funnel(this.funnelRef.current)
> chart.draw(data, options)
> tks you

**Comment by senthilmca90** [comment]
@jakezatecky I added your code. I got the error.

> TypeError: Cannot read property 'style' of null

**Comment by jakezatecky** [comment]
@senthilmca90 That would probably happen if the library cannot find the DOM node (either the ID used points to nothing or something else, or in case of the use of references as with @lucaskeller, the ref may not be properly set).

If that does not help, could you post a live example showcasing the issue?
