### ISSUE TITLE
Multiple Funnels on the same page

### ISSUE THREAD

**Issue by Bigben83** [jakezatecky/d3-funnel#82]
This may be a silly question, but how can you display multiple funnel graphs on the same php page.?

**Comment by jakezatecky** [comment]
You just need multiple DOM containers for D3Funnel to render on. For example:

``` html
<div id="student-pipeline"></div>
<div id="web-visitors"></div>
```

You then need to create an instance of `D3Funnel` for each render target:

``` js
const studentChart = new D3Funnel('#student-pipeline');
studentChart .draw(studentData, options);

const visitorsChart = new D3Funnel('#web-visitors');
visitorsChart.draw(visitorData, options);
```
