### ISSUE TITLE
Static labels

### ISSUE THREAD

**Issue by guventum** [jakezatecky/d3-funnel#83]
Is it possible to make the funnel labels static? With the current version the labels and values reacts to my selections.  For example when I select a year, it only shows the labels of that specific year, the other options dissapear. 

I want all the labels to be shown and that only the values react to selections. 

Kind Regards, 
Guven

**Comment by jakezatecky** [comment]
I am having trouble visualizing what you are referring to. Can you provide some screenshots?

**Comment by guventum** [comment]
For example: 

![funnel](https://user-images.githubusercontent.com/25504724/34556657-7ffae0ba-f137-11e7-9d54-8b43bdb3d1ef.PNG)

On the left funnel it shows all the dimensions but when I make a selection it only shows 1 dimension (right funnel). All other dimension boxes dissapear. So I was wondering if it is possible to keep the original amount of "boxes" so that only the values within those boxes change. 

Do you understand what I mean?

**Comment by jakezatecky** [comment]
Sorry for the extreme lack of response. This appears to be something with a third-party tool using this library (possibly Qlik?). I have no knowledge of how that tool operates and I think the author of that plugin needs to be contacted.

**Comment by jakezatecky** [comment]
Again, I apologize for the long delay since when you last commented and when I replied, but I will be closing this because I believe it is an issue with a third-party tool you are using. If you feel otherwise, please let me know.
