### ISSUE TITLE
Unable to import D3 funnel

### ISSUE THREAD

**Issue by sumedh908** [jakezatecky/d3-funnel#89]
Hi,

I am getting error in ES6 import for D3 funnel.
I have followed the process to load the d3 library in browser before importing d3-funnel.

Approach 1:
`import * as d3 from '../jslibs/d3/d3';
import D3Funnel from 'd3-funnel';`
Have a look at the following.
![sales-funnel-error-es6](https://user-images.githubusercontent.com/38094788/43775880-c5b2a04c-9a6b-11e8-8bc1-8796ebb17933.PNG)

Approach 2: 
I have also tried with 
`import * as D3Funnel from 'd3-funnel';`

but this gives another error
![sales-funnel-error-es6-1](https://user-images.githubusercontent.com/38094788/43776066-5dfcda66-9a6c-11e8-9651-484d6a5b0d02.PNG)

**Comment by jakezatecky** [comment]
Hey there. Sorry for the late response.

Are you using a tool like Webpack to wire in the resources? The screenshots seem to indicate that you may be using ES6 directly in the browser without compilation, which is something I have never done before. If you are doing the latter, then it may be that the import will not work, as the output is UMD.

Can you recreate a simple repository showcasing this issue? I have created a quick repo myself showcasing the import of d3-funnel from npm. This is adapted from the examples page of this repo:

https://github.com/jakezatecky/d3-funnel-import-usage-issue-89

**Comment by jakezatecky** [comment]
Hello. I am closing out this issue due to a lack of response. If you are still having an issue, feel free to reopen this.
