### ISSUE TITLE
When exporting using phantomjs error

### ISSUE THREAD

**Issue by bhikyagolu** [jakezatecky/d3-funnel#92]
`Mahendras-MacBook-Pro-3:~ mahendra$ /Users/mahendra/software/phantomjs-2.1.1-macosx/bin/phantomjs /Users/mahendra/software/phantomjs-2.1.1-macosx/bin/webtoimage_local.js http://localhost/funnelcopy/index.html /Users/mahendra/mywork/tmp/funnel123.png
pageUrl: http://localhost/funnelcopy/index.html
outputImg: /Users/mahendra/mywork/tmp/funnel123.png
TypeError: undefined is not a constructor (evaluating 'Number.isNaN(c)')

  http://localhost/funnelcopy/d3-funnel.js:1
  :0 in forEach
  http://localhost/funnelcopy/d3-funnel.js:1 in value
  http://localhost/funnelcopy/d3-funnel.js:1 in value
  http://localhost/funnelcopy/d3-funnel.js:1 in value
  http://localhost/funnelcopy/index.html:50 in initialize
  http://localhost/funnelcopy/index.html:56 in onload
Status: success
Mahendras-MacBook-Pro-3:~ mahendra$ 
`

Not able to see exact as main js is also minified. 
How can have the d3-funnel.js as non minified version

**Comment by jakezatecky** [comment]
Non-minified version should be fixed and available on v1.2.1.

**Comment by jakezatecky** [comment]
Hello. I am closing out this issue due to a lack of response. If you are still having an issue, feel free to reopen this.
