### ISSUE TITLE
Chart not rendering on React

### ISSUE THREAD

**Issue by Deniscapp** [jakezatecky/d3-funnel#94]
I am trying to use `d3-funnel` with `react` but it didn't work so far.
I have a div: 

`<div style={{ height: 400, width: 400 }} id="funnel"></div>`

on `componentDidMount`:

```

  componentDidMount() {
    const data = [
      { label: 'Inquiries', value: 5000 },
      { label: 'Applicants', value: 2500 },
      { label: 'Admits', value: 500 },
      { label: 'Deposits', value: 200 },
    ];
    const options = {
      chart: {
        height: 400,
        width: 400,
    },
        block: {
            dynamicHeight: true,
            minHeight: 15,
        },
    };

    const chart = new D3Funnel('#funnel');
    chart.draw(data, options);
  }
```
I end up with an empty div with the right height and width, but nothing in there.
Any help on this?
Thanks in advance! :)

**Comment by Deniscapp** [comment]
Sorry, my bad. It worked! 😄

**Comment by arjunINaccolite** [comment]
I am also trying to use d3-funnel with react. I am getting the below error. 
 Cannot read property 'style' of null
    at styleValue (d3-funnel.js:2541)
    at Selection.style (d3-funnel.js:2537)
    at D3Funnel.getContainerDimensions (d3-funnel.js:332)
    at D3Funnel.getSettings (d3-funnel.js:296)
    at D3Funnel.initialize (d3-funnel.js:229)
    at D3Funnel.draw (d3-funnel.js:213)
    at Funnel (Funnel.jsx:24)

I see the container is null for the chart. Is there anything I am missing
